env:
  - ENV_FROM_APPLICATION_YML=true
before_script:
  - mv config/database.yml.travis config/database.yml
rvm:
  - "1.9.3"
bundler_args: --without development
script:
  - bundle exec /usr/bin/env RAILS_ENV=test rake db:drop db:create db:reset
  - bundle exec /usr/bin/env RAILS_ENV=test rspec
  - bundle exec /usr/bin/env RAILS_ENV=test cucumber
notifications:
  email:
    - oneclickcs_github@googlegroups.com
  irc: "irc.freenode.net#oneclick"
after_script:
  - cat "log/test.log"
